import Head from "next/head";
import { Header } from "@/components/Header";
import styles from "@/styles/Home.module.css";
import { signIn, getCsrfToken, getProviders } from "next-auth/react";
const SignIn = ({ csrfToken, providers }) => {
  return (
    <>
      <Head>
        <title>Tasting Note</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Header />

        <main className={styles.main}>
          <div
            className={styles.main_contents}
            style={{ overflow: "hidden", position: "relative" }}
          >
            <h1 className={styles.heading_title}>Sign In</h1>
            <div>
              <input name="csrfToken" type="hidden" defaultValue={csrfToken} />
              <input
                placeholder="Email (Not Setup - Please Use Github)"
                size="large"
              />
              {providers &&
                Object.values(providers).map((provider) => (
                  <div key={provider.name} style={{ marginBottom: 0 }}>
                    <button
                      className={styles.signin_btn}
                      onClick={() =>
                        signIn(provider.id, { callbackUrl: "/beans/selection" })
                      }
                    >
                      Sign in with {provider.name}
                    </button>
                  </div>
                ))}
            </div>
          </div>
        </main>
      </div>
    </>
  );
};
export default SignIn;

// export async function getServerSideProps(context) {
//   const providers = await getProviders();
//   const csrfToken = await getCsrfToken(context);
//   return {
//     props: {
//       providers,
//       csrfToken,
//     },
//   };
// }

// import { signIn, getCsrfToken, getProviders } from "next-auth/react";
// import Image from "next/image";
// import { Header } from "@/components/Header";
// import styles from "@/styles/Sign.module.css";

// const Signin = ({ csrfToken, providers }) => {
//   return (
//     <div style={{ overflow: "hidden", position: "relative" }}>
//       <Header />
//       <div className={styles.wrapper} />
//       <div className={styles.content}>
//         <div className={styles.cardWrapper}>
//           <Image
//             src="../images/katalog_full.svg"
//             width="196"
//             height="64"
//             alt="App Logo"
//             style={{ height: "85px", marginBottom: "20px" }}
//           />
//           <div className={styles.cardContent}>
//             <input name="csrfToken" type="hidden" defaultValue={csrfToken} />
//             <input
//               placeholder="Email (Not Setup - Please Use Github)"
//               size="large"
//             />
//             <button className={styles.primaryBtn}>Submit</button>
//             <hr />
//             {providers &&
//               Object.values(providers).map((provider) => (
//                 <div key={provider.name} style={{ marginBottom: 0 }}>
//                   <button onClick={() => signIn(provider.id)}>
//                     Sign in with {provider.name}
//                   </button>
//                 </div>
//               ))}
//           </div>
//         </div>
//       </div>
//       {/* eslint-disable-next-line @next/next/no-img-element */}
//       <Image
//         src="../images/login_pattern.svg"
//         alt="Pattern Background"
//         layout="fill"
//         className={styles.styledPattern}
//       />
//     </div>
//   );
// };

// export default Signin;

export async function getServerSideProps(context) {
  const providers = await getProviders();
  const csrfToken = await getCsrfToken(context);
  return {
    props: {
      providers,
      csrfToken,
    },
  };
}
