import Head from "next/head";
import { Header } from "@/components/Header";
import { signIn, getCsrfToken, getProviders } from "next-auth/react";
import styles from "@/styles/Home.module.css";

const SignIn = ({ csrfToken, providers }) => {
  return (
    <>
      <Head>
        <title>Tasting Note</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Header />

        <main className={styles.main}>
          <div
            className={styles.main_contents}
            style={{ overflow: "hidden", position: "relative" }}
          >
            <h1 className={styles.heading_title}>Sign In</h1>
            <div>
              <input name="csrfToken" type="hidden" defaultValue={csrfToken} />
              <input
                placeholder="Email (Not Setup - Please Use Github)"
                size="large"
              />
              {providers &&
                Object.values(providers).map((provider) => (
                  <div key={provider.name} style={{ marginBottom: 0 }}>
                    <button
                      className={styles.signin_btn}
                      onClick={() =>
                        signIn(provider.id, { callbackUrl: "/beans/selection" })
                      }
                    >
                      Sign in with {provider.name}
                    </button>
                  </div>
                ))}
            </div>
          </div>
        </main>
      </div>
    </>
  );
};
export default SignIn;

export async function getServerSideProps(context) {
  const providers = await getProviders();
  const csrfToken = await getCsrfToken(context);
  return {
    props: {
      providers,
      csrfToken,
    },
  };
}
